In [12]:
import matplotlib.pyplot as plt
import numpy as np
import torch
from PIL import Image
import math
from glob import glob
from torch.nn import Linear

In [13]:
inp = torch.randn(1, 10)
myLayer = Linear(in_features=10, out_features=5, bias=True)
myLayer(inp)

tensor([[-0.0486, -0.3186, -1.7907, -0.6634, -1.0060]],
       grad_fn=<AddmmBackward0>)

In [14]:
myLayer.weight

Parameter containing:
tensor([[ 0.2069,  0.2340,  0.1736,  0.2935,  0.1787, -0.0943, -0.0173,  0.0796,
          0.0218,  0.0041],
        [-0.0384,  0.0196,  0.1586,  0.2672,  0.3071, -0.1449,  0.0734,  0.2289,
         -0.1221, -0.2597],
        [ 0.2868, -0.3094,  0.0253,  0.3143,  0.0112,  0.1499, -0.2634, -0.2532,
         -0.2510,  0.2198],
        [-0.3141, -0.3058,  0.2646,  0.1236,  0.0582,  0.3111,  0.0239, -0.1031,
          0.2759, -0.0926],
        [ 0.2259, -0.2965,  0.0318, -0.0273,  0.0664,  0.1447, -0.0769, -0.0247,
          0.1217, -0.0304]], requires_grad=True)

In [15]:
myLayer.bias

Parameter containing:
tensor([ 0.0486,  0.0170, -0.0306,  0.2649, -0.1375], requires_grad=True)